name: Bug 报告
description: 在提出问题前请先参阅QUESTION然后升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: "soft-version"
    attributes:
      label: "发生Bug的软件版本"
      description: "请选择出现问题的软件版本"
      options:
        - "请选择..."
        - "v4.9.0-GA"
        - "v4.8.0-GA"
        - "其他版本（请在下方注明）"
    validations:
      required: true
  - type: dropdown
    id: "os-version"
    attributes:
      label: "Windows版本"
      description: "请选择所使用的Windows版本"
      options:
        - "请选择..."
        - "Win11"
        - "Win10"
        - "更老"
    validations:
      required: true
  - type: input
    id: "expectation"
    attributes:
      label: "预期情况"
      description: "描述你认为应该发生什么"
    validations:
      required: true
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "实际情况"
      description: "描述实际发生了什么"
    validations:
      required: true
  - type: textarea
    id: "reproduction-method"
    attributes:
      label: "复现方法"
      description: "在BUG出现前执行了哪些操作"
      placeholder: 标序号
    validations:
      required: true
  - type: textarea
    id: "log"
    attributes:
      label: "日志信息"
      description: "位置在软件当前目录下的log，日志不长时可以直接粘贴日志文本或者日志截图，日志较长需以附加文件的方式"
      placeholder: 在日志开始和结束位置粘贴冒号后的内容：```
    validations:
      required: true
  - type: textarea
    id: "more"
    attributes:
      label: "额外信息"
      description: "可选"
    validations:
      required: false
  - type: checkboxes
    id: "latest-version"
    attributes:
      label: "我确认已更新至最新版本"
      description: "否则请[更新](https://github.com/xjw580/Hearthstone-Script/releases)后尝试"
      options:
        - label: 是
          required: true
  - type: checkboxes
    id: "issues"
    attributes:
      label: "我确认已查询历史issues及参阅常见问题"
      description: "否则请查询及参阅[常见问题](https://github.com/xjw580/Hearthstone-Script/blob/master/doc/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md)后提出"
      options:
        - label: 是
          required: true
