name: Create Release

on:
  push:
    tags:
      - 'v*.*.*-*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine if prerelease
        id: prerelease
        run: |
          if [[ "${{ github.ref_name }}" == *"DEV" ]] || [[ "${{ github.ref_name }}" == *"BETA" ]] || [[ "${{ github.ref_name }}" == *"TEST" ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: Get latest commit message
        id: get_commit
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: hs-script_${{ github.ref_name }}
          body: ${{ steps.get_commit.outputs.message }}
          prerelease: ${{ env.prerelease }}
        env:
          GITHUB_TOKEN: ${{ github.token }}